export const vehicles = [
  {
    id: 1,
    busNumber: "KA-01-1234",
    routeNumber: "101",
    routeName: "Main Street - Central Park",
    drivername: "John Doe",
    contactNumber: "9876543210",
    speedLimit: 60,
    seatCount: 40,
    busId: "BUS001",
    busName: "City Express",
    status: "Active",
    createdAt: "2025-02-10 08:30:00",
    updatedOn: "2025-02-10 12:45:00",
  },
  {
    id: 2,
    busNumber: "KA-02-5678",
    routeNumber: "102",
    routeName: "Downtown - Airport",
    drivername: "Jane Smith",
    contactNumber: "9876543220",
    speedLimit: 70,
    seatCount: 50,
    busId: "BUS002",
    busName: "Metro Link",
    status: "Inactive",
    createdAt: "2025-02-10 09:00:00",
    updatedOn: "2025-02-10 13:00:00",
  },
  {
    id: 3,
    busNumber: "KA-03-9101",
    routeNumber: "103",
    routeName: "Uptown - Station",
    drivername: "Robert Brown",
    contactNumber: "9876543230",
    speedLimit: 65,
    seatCount: 45,
    busId: "BUS003",
    busName: "Rapid Transit",
    status: "Active",
    createdAt: "2025-02-10 10:15:00",
    updatedOn: "2025-02-10 14:10:00",
  },
];

export const drivers = [
  {
    id: 1,
    driverName: "John Doe",
    driverEmail: "john.doe@example.com",
    status: "Active",
    createdAt: "2025-02-10 08:30:00",
  },
  {
    id: 2,
    driverName: "Jane Smith",
    driverEmail: "jane.smith@example.com",
    status: "Inactive",
    createdAt: "2025-02-10 09:45:00",
  },
];

// export const announcements = [
//   {
//     id: 1,
//     snederName: "John Doe",
//     employeeName: "Alice Smith",
//     title: "Project Update",
//     message: "The project is on track and will be completed by next week.",
//     createdOn: "2024-02-11 10:30 AM",
//   },
//   {
//     id: 2,
//     snederName: "Jane Smith",
//     employeeName: "Bob Johnson",
//     title: "Meeting Reminder",
//     message: "Reminder: Team meeting scheduled for tomorrow at 10 AM.",
//     createdOn: "2024-02-10 03:15 PM",
//   },
//   {
//     id: 3,
//     snederName: "Michael Brown",
//     employeeName: "Charlie Davis",
//     title: "Task Assignment",
//     message: "Please complete the assigned task by Friday.",
//     createdOn: "2024-02-09 09:45 AM",
//   },
//   {
//     id: 4,
//     snederName: "Emily Wilson",
//     employeeName: "David Miller",
//     title: "Holiday Notice",
//     message: "Office will remain closed on 14th Feb for maintenance.",
//     createdOn: "2024-02-08 05:20 PM",
//   },
//   {
//     id: 5,
//     snederName: "William Taylor",
//     employeeName: "Emma Johnson",
//     title: "Policy Update",
//     message: "New company policies have been updated. Please review them.",
//     createdOn: "2024-02-07 11:10 AM",
//   },
// ];

// export const emergencyAlert = [
//   {
//     id: 1,
//     date: "2024-02-11",
//     vehicleNo: "MH12AB1234",
//     routeNo: "R001",
//     routeName: "Pune - Mumbai",
//     driverName: "Rajesh Kumar",
//     employeeName: "Amit Sharma",
//     employeeId: "EMP1001",
//     title: "Speed Violation",
//     message: "Vehicle exceeded speed limit of 80km/h.",
//     actionTaken: "Driver warned and notified.",
//   },
//   {
//     id: 2,
//     date: "2024-02-10",
//     vehicleNo: "MH14XY5678",
//     routeNo: "R002",
//     routeName: "Mumbai - Nashik",
//     driverName: "Sunil Patil",
//     employeeName: "Ravi Verma",
//     employeeId: "EMP1002",
//     title: "Route Deviation",
//     message: "Vehicle deviated from the assigned route.",
//     actionTaken: "Route correction advised.",
//   },
//   {
//     id: 3,
//     date: "2024-02-09",
//     vehicleNo: "DL10CD9087",
//     routeNo: "R003",
//     routeName: "Delhi - Jaipur",
//     driverName: "Suresh Mehta",
//     employeeName: "Vikas Gupta",
//     employeeId: "EMP1003",
//     title: "Unauthorized Stop",
//     message: "Vehicle stopped for 30 minutes at an unauthorized location.",
//     actionTaken: "Driver questioned; further monitoring enabled.",
//   },
//   {
//     id: 4,
//     date: "2024-02-08",
//     vehicleNo: "KA05PQ2345",
//     routeNo: "R004",
//     routeName: "Bangalore - Mysore",
//     driverName: "Prakash Rao",
//     employeeName: "Manoj Iyer",
//     employeeId: "EMP1004",
//     title: "Low Fuel Alert",
//     message: "Fuel level dropped below 10%.",
//     actionTaken: "Driver directed to nearest fuel station.",
//   },
//   {
//     id: 5,
//     date: "2024-02-07",
//     vehicleNo: "TN07GH6789",
//     routeNo: "R005",
//     routeName: "Chennai - Coimbatore",
//     driverName: "Anand Krishnan",
//     employeeName: "Sridhar Nair",
//     employeeId: "EMP1005",
//     title: "Engine Malfunction",
//     message: "Engine temperature exceeded safe limits.",
//     actionTaken: "Mechanic dispatched for inspection.",
//   },
// ];

// export const routeChangeRequest = [
//   {
//     id: 1,
//     name: "Amit Sharma",
//     employeId: "EMP001",
//     plant: "Plant A",
//     department: "Manufacturing",
//     routeName: "Route Alpha",
//     routeNo: "R001",
//     routeNoOld: "R098",
//     boardingPointOld: "Gate 1",
//     boardingPointNew: "Gate 3",
//     approvedBy: "Manager A",
//     approvedOn: "2024-02-10",
//     status: "Approved",
//     createdAt: "2024-02-05",
//   },
//   {
//     id: 2,
//     name: "Priya Verma",
//     employeId: "EMP002",
//     plant: "Plant B",
//     department: "Quality Control",
//     routeName: "Route Beta",
//     routeNo: "R002",
//     routeNoOld: "R099",
//     boardingPointOld: "Gate 2",
//     boardingPointNew: "Gate 4",
//     approvedBy: "Manager B",
//     approvedOn: "2024-02-09",
//     status: "Pending",
//     createdAt: "2024-02-06",
//   },
//   {
//     id: 3,
//     name: "Rahul Mehta",
//     employeId: "EMP003",
//     plant: "Plant C",
//     department: "Logistics",
//     routeName: "Route Gamma",
//     routeNo: "R003",
//     routeNoOld: "R100",
//     boardingPointOld: "Gate 3",
//     boardingPointNew: "Gate 5",
//     approvedBy: "Manager C",
//     approvedOn: "2024-02-08",
//     status: "Rejected",
//     createdAt: "2024-02-07",
//   },
// ];

// export const feedback = [
//   {
//     id: 1,
//     employeeName: "Amit Sharma",
//     rating: 4.5,
//     message: "Great performance and teamwork.",
//     createdAt: "2024-02-10",
//   },
//   {
//     id: 2,
//     employeeName: "Priya Verma",
//     rating: 3.8,
//     message: "Needs improvement in time management.",
//     createdAt: "2024-02-09",
//   },
//   {
//     id: 3,
//     employeeName: "Rahul Mehta",
//     rating: 5.0,
//     message: "Outstanding contribution to the project.",
//     createdAt: "2024-02-08",
//   },
//   {
//     id: 4,
//     employeeName: "Sneha Roy",
//     rating: 4.2,
//     message: "Good communication skills.",
//     createdAt: "2024-02-07",
//   },
//   {
//     id: 5,
//     employeeName: "Vikram Singh",
//     rating: 3.5,
//     message: "Requires better coordination with the team.",
//     createdAt: "2024-02-06",
//   },
// ];

export const vehicleRoutes = [
  {
    id: 1,
    busNumber: "MH-12-AB-1234",
    routeName: "Route Alpha",
    busDriver: "Rajesh Kumar",
    status: "Active",
    createdAt: "2024-02-10",
  },
  {
    id: 2,
    busNumber: "MH-14-CD-5678",
    routeName: "Route Beta",
    busDriver: "Suresh Yadav",
    status: "Inactive",
    createdAt: "2024-02-09",
  },
  {
    id: 3,
    busNumber: "MH-16-EF-9101",
    routeName: "Route Gamma",
    busDriver: "Amit Sharma",
    status: "Active",
    createdAt: "2024-02-08",
  },
  {
    id: 4,
    busNumber: "MH-18-GH-1121",
    routeName: "Route Delta",
    busDriver: "Sunil Verma",
    status: "Maintenance",
    createdAt: "2024-02-07",
  },
  {
    id: 5,
    busNumber: "MH-20-IJ-3141",
    routeName: "Route Epsilon",
    busDriver: "Vikas Singh",
    status: "Active",
    createdAt: "2024-02-06",
  },
];

export const geofence = [
  {
    id: 1,
    busName: "City Express",
    geofenceName: "Main Street",
    geofenceType: "Exit",
    createdAt: "2024-02-10",
  },
  {
    id: 2,
    busName: "Metro Link",
    geofenceName: "Downtown",
    geofenceType: "Entry",
    createdAt: "2024-02-09",
  },
  {
    id: 3,
    busName: "City Express",
    geofenceName: "Main Street",
    geofenceType: "Exit",
    createdAt: "2024-02-08",
  },
  {
    id: 4,
    busName: "Metro Link",
    geofenceName: "Downtown",
    geofenceType: "Entry",
    createdAt: "2024-02-07",
  },
];
